In [ ]:
pip install numpy

In [ ]:
import numpy as np
print(np.__version__)

2.1.3


In [ ]:
import numpy as np
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
import numpy as np
arr = np.ones((5,7))
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np
arr = np.full((4,7),9)
print(arr)

[[9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]]


In [ ]:
import numpy as np
arr = np.empty((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
import numpy as np
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np
arr = np.arange(1,101,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [ ]:
import numpy as np
Even= np.arange(2,200,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [ ]:
import numpy as np
arr = np.linspace(1,20,7)
print(arr)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [ ]:
import numpy as np
arr=np.random.rand(10)
print(arr)

[0.72029827 0.64089689 0.04159628 0.63713035 0.7342194  0.88136837
 0.08783453 0.75538412 0.97069459 0.11823683]


In [ ]:
import numpy as np
arr = np.random.randint(100)
print(arr)

51


In [ ]:
import numpy as np
colours = ["red","green","pink","orange","blue","white","black"]
print(np.random.choice(colours,2))

['pink' 'black']


In [ ]:
import numpy as np
arr = np.array([1,2,3])
new = arr.copy()
new[1] = 100
print("Array value is :",arr)
print("copy value is :",new)

Array value is : [1 2 3]
copy value is : [  1 100   3]


In [ ]:
import numpy as np
arr=np.array([5,10,15,20,25,30])
arr +=10
print("updated array value is:",arr)


updated array value is: [15 20 25 30 35 40]


In [ ]:
import numpy as np
A = np.array([1,2,3,4,5])
B = np.array([6,7,8,9,10])
print(np.add(A,B))

[ 7  9 11 13 15]


In [ ]:
import numpy as np
Arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(sum(arr))

165


In [ ]:
import numpy as np

Arr = np.array([5, 8, 2, 9, 2, 0, 1, 6, 4, 8])

print(np.sort(Arr))

[0 1 2 2 4 5 6 8 8 9]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.itemsize)

(9,)
9
1
8


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(arr.shape)
print(arr.ndim)
print(arr[0, 1])
print(arr[1, 1])
print(arr[:, 1])

(2, 4)
2
2
6
[2 6]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4,5, 6, 7, 8,9,10,11,12,13,14,15])
print("original Array",arr)
new = arr.reshape(3,5)
print(new)

original Array [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
